# Generated by Django 4.2.11 on 2024-04-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarefa_aleatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='aleatorio',
        ),
    ]
